### ISSUE TITLE
Build Host and push nuget package to our internal DevOps Artifacts feed 

### ISSUE THREAD

**Issue by Francisco-Gamino** [Azure/azure-functions-integration-tests#3]
Update existing Host pipeline to update the references of the packages for the PowerShell worker, build Host bits using the build-extensions.ps1 script. Push nuget package to our internal DevOps Artifacts feed

**Comment by fabiocav** [comment]
Is there a reason why we want a dedicated build for the host as opposed to working with the published artifacts from the host build?

**Comment by Francisco-Gamino** [comment]
Hi @madelinegordon -- I am adding a few more details for this work item.

1) Modify existing build script located at https://github.com/Azure/azure-functions-host/blob/dev/build/build-extensions.ps1

  * Add a new parameter, e.g., `$nightlyBuild`. I would suggest using a `switch` instead of a `boolean`

  * Add the logic to update the reference to the PowerShell worker. As per our discussion, we will create a list of workers that haven been onboarded to build the Host. We can retrieve this list during the build process. However, for now just focus on the PowerShell worker.
  * Once you have modified the build script, test your changes to make sure the script continues to work without the $nightlyBuild flag.
  * Once everything is working locally, please send a PR and add @pragnagopa and me to review it.

2) Next, update Host pipeline
* Add a new bool variable named `$nightlyBuild` and set it to `$false` by default. These means that the stages below will only execute if `$nightlyBuild` and set it to `$true`
* Add a stage to copy the nuget package to the `ArtifactStagingDirectory` (if needed). Here is some sample code that does that for the PowerShell worker:
```powershell
$packageName = 'Microsoft.Azure.Functions.PowerShellWorker'
$sourcePath  = (ls package/**/*/$packageName*.nupkg).FullName
      if (-not (test-path $sourcePath))
      {
        throw 'Unable to find $packageName*.nupkg at ./package'
      }
      Copy-Item -Path $sourcePath -Destination $(Build.ArtifactStagingDirectory) -ErrorAction Stop -Verbose -Force
```
* Lastly, add a stage to push the nuget package to the feed. To do this, go to the pipeline and click `Edit`. Select the area in the yml file where you would like add the stage, in this case the end of the file. 

  On the Tasks section on the right type "push". From there, select NuGet. After that, set the following fields (highlighted in yellow):
   **Command** is push
   **Target feed** is the name of our feed
   Check **Allow duplicates to be skipped**

![image](https://user-images.githubusercontent.com/12720858/90279743-9d707700-de1e-11ea-998b-94267abbae18.png)
